### ISSUE TITLE
About using json to save article?

### ISSUE THREAD

**Issue by wi1d5ky** [isdampe/Notedown#14]
Is there any probability not to use json to save articles?
I think it will be at sixes and seven when there are more and more articles

**Comment by isdampe** [comment]
In it's current form, I think we'll stick with JSON for the simplicity. Perhaps down the track if the app had greater support, and maybe more sorting / categorising features for notes, we'd switch to something more robust. Keep in mind a flat JSON file is very simple for people to backup / edit where required.
