### ISSUE TITLE
No support for shortcuts such as copy/paste?

### ISSUE THREAD

**Issue by voigt** [isdampe/Notedown#4]
Hi,

Notedown is exactly what I am looking for. After a short try it turned out, that copy/paste (cmd + c/v) doesn't work. Is this a bug or the desired behaviour?

Hope you keep up the work!
Christoph

**Comment by isdampe** [comment]
Hey mate,

Cheers,
What OS are you running on? Sounds like OSX

I'll check it out when I get a chance to jump on my OSX machine - the shortcut keys are working on Win32/Linux.

**Comment by voigt** [comment]
Yep, OSX Mavericks.

I googled around and it seems to be a known issue: https://github.com/nwjs/nw.js/issues/1955

**Comment by isdampe** [comment]
Thanks for the feedback - looks like there's a fix.

I'll jump on my OSX machine and have a play and patch it.

**Comment by isdampe** [comment]
Fixed with df0fe3224966e15a330235686a70ff2afbbca67e.

Cheers for the help.
